### ISSUE TITLE
Can you tell me how to set the beautiful profile in md.file?

### ISSUE THREAD

**Issue by sunshinewhy** [Coolshanlan/Coolshanlan#1]
I notice that your profile is beautiful, how did you do it? Thanks!

**Comment by Coolshanlan** [comment]
Thanks for your appreciation!
1. You can see [this repo](https://github.com/anuraghazra/github-readme-stats) to create beatiful git staus views
2. I genrated my introduction animation from [this website](https://pixelspeechbubble.com/)
3. You can google search "github git stats" or use[ this website](https://awesome-github-stats.azurewebsites.net/)

Hope these will be helpful.

**Comment by sunshinewhy** [comment]
> Thanks for your appreciation!
> 
> 1. You can see [this repo](https://github.com/anuraghazra/github-readme-stats) to create beatiful git staus views
> 2. I genrated my introduction animation from [this website](https://pixelspeechbubble.com/)
> 3. You can google search "github git stats" or use[ this website](https://awesome-github-stats.azurewebsites.net/)
> 
> Hope these will be helpful.

@Coolshanlan Got it. Thanks a lot!
